/**
 * @module audio-engine/synth
 *
 * Core synthesis routines.  The synthesiser generates a floating‑point
 * waveform from a set of physical parameters by modelling electrical hum,
 * mechanical resonance, optional driver whine, white noise and, for the
 * photoacoustic model, a first‑order thermal process.  It delegates
 * waveform generation to the {@link module:models/waveforms} module and
 * filtering to the {@link module:models/filters} module.
 */

import { waveSample } from '../models/waveforms.js';
import { applyBandPass } from '../models/filters.js';

/** Clamp a number to the range [`min`, `max`]. */
function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

/**
 * Synthesize an audio buffer for the given parameter set.  The algorithm
 * consists of three stages:
 *  1.  A dry signal is generated by modulating a waveform according to
 *      `params.baseFreq`, `params.waveform`, `params.depth`, and mode
 *      specific processing (sonification, photoacoustic thermal model or
 *      direct electrical modulation).
 *  2.  Optional high‑frequency whine and noise terms are added.
 *  3.  A resonant band‑pass filter shapes the spectral content and the
 *      filtered signal is mixed with the dry signal.  The result is
 *      normalised and scaled by `params.gain`.
 *
 * @param {import('../presets/index.js').Params} params Synthesis parameters.
 * @param {number} seconds                      Length of the output in seconds.
 * @param {number} [sampleRate=48_000]         Sampling rate in hertz.
 * @returns {Float32Array} Normalised audio samples in the range [−1, 1].
 */
export function synthesize(params, seconds, sampleRate = 48_000) {
  const total = Math.floor(seconds * sampleRate);
  const dry = new Float32Array(total);
  // Precompute the thermal filter alpha for the photoacoustic model.  The
  // single‑pole low‑pass has the continuous‑time form τ·dT/dt = I(t) − T.
  // In discrete time the update coefficient is 1 − exp(−2π f_c / fs).
  const alpha = 1 - Math.exp((-2 * Math.PI * Math.max(0.1, params.thermalCutoff)) / sampleRate);
  let thermal = 0;
  let prevThermal = 0;
  // Seed for reproducible pseudo‑random noise (linear congruential generator)
  let seed = 1337;
  for (let i = 0; i < total; i += 1) {
    const t = i / sampleRate;
    const rawWave = waveSample(t, params.baseFreq, params.waveform, params.duty);
    // Modulate the light intensity between 0 and 1
    const light = clamp(0.5 + 0.5 * params.depth * rawWave, 0, 1);
    let x = 0;
    // Mode‑dependent conversion to an audible signal
    if (params.lowFreqSonify || params.baseFreq < 20) {
      // Sonification maps slow modulation onto an audible carrier
      const carrier = Math.sin(2 * Math.PI * params.carrierFreq * t);
      x = (light - 0.5) * carrier * 2;
    } else if (params.mode === 'photoacoustic') {
      // Simple thermal model: low‑pass filter followed by time derivative
      thermal += alpha * (light - thermal);
      x = (thermal - prevThermal) * sampleRate * 0.01;
      prevThermal = thermal;
    } else {
      // Direct electrical model: subtract DC offset to centre around zero
      x = light - 0.5;
    }
    // Add a whine (e.g. from switching regulators)
    if (params.whineFreq > 0 && params.whineLevel > 0) {
      x += params.whineLevel * Math.sin(2 * Math.PI * params.whineFreq * t);
    }
    // Add white noise using a reproducible LCG
    if (params.noiseLevel > 0) {
      seed = (1664525 * seed + 1013904223) >>> 0;
      const noise = (seed / 0xffffffff) * 2 - 1;
      x += noise * params.noiseLevel;
    }
    dry[i] = x;
  }
  // Apply a second‑order band‑pass filter to model resonant structures
  const wet = applyBandPass(dry, sampleRate, params.resonanceHz, params.resonanceQ);
  const mixed = new Float32Array(total);
  const mix = clamp(params.resonanceMix, 0, 1);
  let peak = 1e-6;
  for (let i = 0; i < total; i += 1) {
    const y = (1 - mix) * dry[i] + mix * wet[i];
    mixed[i] = y;
    peak = Math.max(peak, Math.abs(y));
  }
  // Normalise and apply gain.  0.95 prevents full‑scale clipping when the mix
  // emphasises resonance peaks.
  const normalise = Math.min(1, 0.95 / peak);
  for (let i = 0; i < total; i += 1) {
    mixed[i] = clamp(mixed[i] * normalise * params.gain, -1, 1);
  }
  return mixed;
}